spring:

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    me.silvernine: DEBUG

jwt:
  header: Authoriaztion
  secret: aGVvc2VvbmdoeWVvbnNlb25naHllb25oZW9zZW9uZ2h5ZW9oZW9zZW9uZ2h5ZW9uc2VvbmdoeWVvbmhlb3Nlb25naHllbwo
  token-validity-in-seconds: 86400